### ISSUE TITLE
Can’t Install Paid Tweaks from Twickd Repo

### ISSUE THREAD

**Issue by javatlc** [zbrateam/Zebra#1354]
**Describe the bug**
When I try to install or upgrade tweaks that I have bought from the Twickd repo, the app scans my face with FaceID but then nothing happens. I have had to go back to Cydia to install these tweaks.

**To Reproduce**
To reproduce this I press install or modify on a paid tweak from Twickd that I have already purchased. Zebra shows the FaceID scan hud and my face is accepted but then nothing happens. The package does queue to install or upgrade.

**Expected behavior**
After pressing install or upgrade, and having my face scanned, I expected Zebra to queue the tweak for installation. 

**Screenshots**

**Device Information (please complete the following information):

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta1b
 - Device Type [e.g. iPhone or iPad]: iPhone 11 Pro Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
I believe this was fixed in the 1.1.10 version, could you downgrade and check?

**Comment by javatlc** [comment]
Thanks for the reply. I downgraded Zebra to 1.1.1 and I’m still having the
same issue. If theres anything else I can do to help please let me know.

On Sun, Jun 7, 2020 at 4:28 PM Wilson Styres <notifications@github.com>
wrote:

I believe this was fixed in the 1.1.10 version, could you downgrade and
check?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wstyres/Zebra/issues/1354#issuecomment-640275036>, or
unsubscribe

**Comment by wstyres** [comment]
Make sure it is 1.1.10 and not 1.1.1

**Comment by javatlc** [comment]
Sorry, I did do 1.1.10 this time but still the same result.

On Sun, Jun 7, 2020 at 6:48 PM Wilson Styres <notifications@github.com>
wrote:

Make sure it is 1.1.10 and not 1.1.1

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wstyres/Zebra/issues/1354#issuecomment-640291426>, or
unsubscribe

**Comment by wstyres** [comment]
Could you post a screen recording of the problem?

**Comment by javatlc** [comment]
I attached a screen recording

On Sun, Jun 7, 2020 at 7:33 PM Wilson Styres <notifications@github.com>
wrote:

Could you post a screen recording of the problem?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wstyres/Zebra/issues/1354#issuecomment-640296427>, or
unsubscribe

**Comment by javatlc** [comment]
I’m also getting an error when trying to buy a package from Packix. I
attached another screen recording.

On Sun, Jun 7, 2020 at 7:47 PM Thomas Cruz <t.l.cruz97@gmail.com> wrote:


I attached a screen recording

On Sun, Jun 7, 2020 at 7:33 PM Wilson Styres <notifications@github.com>
wrote:

Could you post a screen recording of the problem?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wstyres/Zebra/issues/1354#issuecomment-640296427>, or
unsubscribe

**Comment by wstyres** [comment]
Looks like neither of your screen recordings were uploaded, you’ll need to upload them to a site like imgur and paste a link because attaching things via email does not work.

**Comment by javatlc** [comment]
Sorry about that, here you go.
https://imgur.com/gallery/iWftXWb

On Mon, Jun 8, 2020 at 7:36 PM Wilson Styres <notifications@github.com>
wrote:

Looks like neither of your screen recordings were uploaded, you’ll need to
upload them to a site like imgur and paste a link because attaching things
via email does not work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wstyres/Zebra/issues/1354#issuecomment-640942279>, or
unsubscribe

**Comment by b1tbucket** [comment]
I have the same problem with the latest release and beta

**Comment by holakooo** [comment]
Hello how are you?  I purchased a 1.99 paid depth theme a week ago and cannot download it now. The payment sign required by Face ID appears :(

**Comment by holakooo** [comment]
![Uploading 8A5A2435-6388-44DA-A597-3176378A00B0.jpeg…]()

**Comment by iAdam1n** [comment]
You need to login under Stores>Packix (same with Twickd).
