### ISSUE TITLE
No Packages under “Author”

### ISSUE THREAD

**Issue by TonyGstring** [zbrateam/Zebra#1654]
**Describe the bug**
When tapping on “Author” at the bottom of a package description page to find other tweaks created by that developer, it brings up a blank and empty black screen (as if no packages exist under that “Author”, even including the original one) instead of listing more packages developed by the same “Author”. 

**To Reproduce**
Open Zebra in order to tap on a package using any of the various tabs (ie: search, installed packages, changes, etc.), then scroll down all the way to the end and click on “Author”. 

**Expected behavior**
A list of (all?) packages with the same “Author”. 

**Screenshots**

**Device Information:** 
 - iOS Version: 13.5
 - Zebra Version: 1.2~beta6a
 - Device Type: iPhone XR
 - Jailbreak Type: unc0ver

**Crash Log or System Log**

**Additional context**

**Comment by eve0415** [comment]
This is fixed in beta7b

**Comment by wstyres** [comment]
I'm still able to reproduce this issue. I don't think it's fixed.

**Comment by wstyres** [comment]
Should be fixed as of a77dadd09a7c873b23da0a803605adca75ccb0e3.

**Comment by TonyGstring** [comment]
> This is fixed in beta7b

While on beta6a, I didn't receive an update notification or badge for some reason but so far on beta7b (even tho the latest release listed here is 7a?), it appears to work intermittently, depending on the repo. 
I am not sure if it's up to the repos for support as a server-side issue or not, but that's what seemed to correlate in my brief testing. Now, whether that's a common denominator or just a coincidence, I couldn't tell you.

**Comment by eve0415** [comment]
Not fixed in beta7d

**Comment by PoomSmart** [comment]
@eve0415 Which package(s) did you test?

**Comment by eve0415** [comment]
Everything.
![image](https://user-images.githubusercontent.com/40632436/103403804-cb1f4800-4b94-11eb-9afe-791238a4ec9d.png)

**Comment by PoomSmart** [comment]
Property fixed in https://github.com/zbrateam/Zebra/pull/1696
