### ISSUE TITLE
NSPhotoLibraryAddUsageDescription missing

### ISSUE THREAD

**Issue by CySxL** [zbrateam/Zebra#2001]
**Describe the bug**
Zebra crashes immediately after press "save to Photo" option in Force Touch menu on preview images.

**To Reproduce**
<1.> Launch Zebra
<2.> Find a tweak with preview images provided
<3.> Force touch/3D touch the image
<4.> Choose "save to Photo" option
<5.> Zebra crashes

**Expected behavior**
Successfully save images without app crash

**Screenshots**
No screenshots.

**Device Information:** 

 - iOS Version: <14.8>
 - Zebra Version: <1.1.28>
 - Device Type: <iPhone 11 Pro Max>
 - Jailbreak Type: <unc0ver 8.0.2>

**Crash Log or System Log**
File : https://discord.com/channels/566255609251364864/566255609251364867/1037446032444883025
![image](https://user-images.githubusercontent.com/15531137/199581990-1cbb8885-119e-4a2b-8a5c-7ce1b3402e58.jpeg)

**Additional context**

**Comment by kirb** [comment]
Thanks for catching and reporting this! I did catch this myself once but forgot to make a note of it. Kinda silly that a WebKit feature requires the app to gain photo library permission 🙄

**Comment by CySxL** [comment]
> Thanks for catching and reporting this! I did catch this myself once but forgot to make a note of it. Kinda silly that a WebKit feature requires the app to gain photo library permission 🙄 

Hahaha 😂 No worries! It's my honor to help.

**Comment by kirb** [comment]
Fixed in 1.1.29. Thanks again for reporting!

**Comment by CySxL** [comment]
> Fixed in 1.1.29. Thanks again for reporting!

Tested and I still have the crash after pressing "save to Photo" 😂

**Comment by kirb** [comment]
Ahh… yep I thought I fixed it, but I just realised I actually forgot to add the file to the Xcode build 🤦‍♀️ I’ll get it *actually* fixed in the next release then.

**Comment by CySxL** [comment]
> Ahh… yep I thought I fixed it, but I just realised I actually forgot to add the file to the Xcode build 🤦‍♀️ I’ll get it *actually* fixed in the next release then.

no worries 😂😂

**Comment by iAdam1n** [comment]
1.1.30 has been released and includes this fix.

**Comment by CySxL** [comment]
> 1.1.30 has been released and includes this fix.

confirmed fixed too ! Thanks for your hard work !
